# Generated by Django 5.1.3 on 2025-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_orderproduct_alter_product_name_cartline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproject',
            name='title',
            field=models.TextField(default='No title'),
        ),
    ]
