# Generated by Django 5.1.3 on 2025-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customproject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproject',
            name='title',
            field=models.CharField(default='No title', max_length=128),
        ),
    ]
