# Generated by Django 5.1.3 on 2025-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customproject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
