# Generated by Django 5.1.3 on 2025-02-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cart_customerid_alter_order_customerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='processed',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Trg Bana Josipa Jelacica 10, 10000 Zagreb, Croatia', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
