# Generated by Django 5.1.3 on 2025-02-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_email_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
