# Generated by Django 5.1.3 on 2025-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderline_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproject',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
